version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt -r requirements-dev.txt
  pre_build:
    commands:
      - echo "Lint + Tests"
      - flake8 . || true
      - export PYTHONPATH=$CODEBUILD_SRC_DIR
      - pytest -q
      - echo "Logging into ECR..."
      - echo "AWS_REGION=$AWS_REGION"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - echo "ECR_URI=$ECR_URI"
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI
      - COMMIT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_SHA:-latest}
      - echo "AWS_REGION=$AWS_REGION"

  build:
    commands:
      - echo "Build Docker image"
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_URI/$ECR_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo "Push image"
      - docker push $ECR_URI/$ECR_REPO:$IMAGE_TAG
      - echo "Writing imagedefinitions.json"
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$ECR_URI/$ECR_REPO:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
